### PR TITLE
Allows collection contain different classes

### PR DESCRIPTION
**Pull request by dotfry**
The ability for an `Operation` to contain a `Parameter` or `Reference` at the same time as it defined in phpdoc.

### CODE REVIEW

**Comment by allansun** [comment]
@dotfry Thanks for your PR.

Could you parse your JSON and highlight your particular code requires this change?

This project is not in stable status since I've only recently converted it from my old project https://github.com/allansun/kubernetes-php-client , however it has been running fine generating code from Kubernetes's Swagger JSON. So I wonder under what situation you would want to change it this way.

Sorry due to the complexity of OpenAPI specs, I developed this project without writing much unit tests, so we have to run functional tests against live spec files, for now.

**Comment by dotfry** [comment]
Sure, example is:
```yaml
swagger: '2.0'
info:
    title: Test
    description: Test processing service
    version: 65.5.35
    license:
        name: proprietary
    contact:
        url: 'https://example.com/readme'
host: localhost
schemes:
    - http
consumes:
    - application/json
produces:
    - application/json
paths:
    /tests:
        post:
            tags:
                - Tag1
            summary: Create test.
            operationId: CreateTest
            description: 'Create test data by test id, test hash or test uuid.'
            parameters:
                - $ref: '#/parameters/RandomParameter' # ← this
                - name: body # ← and this
                  in: body
                  required: true
                  schema:
                      $ref: '#/definitions/Error'
            responses:
                '400':
                    description: Bad request.
                    schema:
                        $ref: '#/definitions/Error'
                '500':
                    description: Internal server error.
                    schema:
                        $ref: '#/definitions/Error'
parameters:
    RandomParameter:
        in: header
        type: string
        name: X-Random-Param
        required: false
definitions:
    Error:
        type: object
        required:
            - message
        description: Error message
        properties:
            message:
                type: string
```

**Comment by allansun** [comment]
I see... you are using a Swagger(v2) spec, I've only been working on the OpenAPI (v3) spec, I haven't got time to check the code on v2 yet, I'm sure it is NOT working at the moment...Leave that with me, I'll see what I can do today.

**Comment by allansun** [comment]
@dotfry After revisiting the code I do agree the code is buggy. However your PR doesn't seem to solve the problem

I have made some changes and pushed a new version (2.1.4). Give it a try, I've used your sample YAML to test and it passed.

**Comment by allansun** [comment]
You may also want to have a look at https://github.com/allansun/openapi-code-generator, which utilise this openapi-parser to do automatic code generation (which is the whole purpose I created this lib).

Beware the Swagger version of code generator is not checked and expected to be NOT working 😂 

I'm recently working on OpenAPI version and that's working now. I really should have spent some time on fixing the Swagger version so I can port my kubernetes-client lib to use this lib...

**Comment by allansun** [comment]
I will close this PR since my change seemed to solve your problem.

**Pull request closed without merging**
